name: pr-tests
run-name: Triggered by ${{ github.actor }} on PR and Push
on:
  pull_request:
  push:

jobs:
  createPullRequest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - id: generatePrNumber
        run: |
          PR_PATH=${{ secrets.GITHUB_REF }} node ci-cd/lighthouse/write-pr-number.js && prNumber=$(cat pr-number.txt)
      - id: renderTemplate
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
          vars: |
            prNumber: ${{ steps.generatePrNumber.outputs.prNumber }}
      - id: pullRequest
        uses: peter-evans/create-pull-request@v4
        with:
          body: ${{ steps.renderTemplate.outputs.result }}
      - id: batman
        run: |
          echo "${{ github.actor }}"


  run-lighthouse-tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: echo "I am the second job"
