name: pr-tests
run-name: Triggered by ${{ github.actor }} on PR and Push
on:
  pull_request:
  push:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - id: getPrNumber
        run: |
          echo "prNumber=$(REF=${{ github.ref }} PR_NUMBER=${{ github.event.pull_request.number }} node ci-cd/lighthouse/write-pr-number.js)" >> $GITHUB_OUTPUT
      - if: steps.getPrNumber.outputs.prNumber != ''
        id: renderTemplate
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
          vars: |
            prNumber: ${{ steps.getPrNumber.outputs.prNumber }}
            prNoomber: $(REF=${{ github.ref }} PR_NUMBER=${{ github.event.pull_request.number }} node ci-cd/lighthouse/write-pr-number.js)
      - if: steps.getPrNumber.outputs.prNumber != ''
        id: updatePullRequest
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '(\w|\W)+'
          head-branch-regex: '(\w|\W)+'
          body-template: ${{ steps.renderTemplate.outputs.result }}
          body-update-action: 'suffix'
          body-uppercase-base-match: false
