name: performance-tests
run-name: Triggered by ${{ github.actor }} on every PUSH
on:
  push:
    branches:
      - main
jobs:
  run-lighthouse-tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: cd src && node plainpuppeteer.js
      - run: git add . && git commit -m "Lighthouse tests" && git push origin docs -f
