name: performance-tests
run-name: Triggered by ${{ github.actor }} on every PUSH
on: [push]
jobs:
  run-lighthouse-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: cd src
      - run: node plainpuppeteer.js