name: pr-tests
run-name: Triggered by ${{ github.actor }} on PR and Push
on:
  pull_request:
  push:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - id: generatePrNumber
        run: |
          REF=${{ github.ref }} PR_NUMBER=${{ github.event.pull_request.number }} node ci-cd/lighthouse/write-pr-number.js && prNumber=$(cat pr-number.txt)
      - id: renderTemplate
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
          vars: |
            prNumber: ${{ steps.generatePrNumber.outputs.prNumber }}
      - id: pullRequest
        uses: peter-evans/create-pull-request@v4
        with:
          body: ${{ steps.renderTemplate.outputs.result }}
      - id: batman
        run: |
          echo "${{ github.actor }}"

  displayPr:
    runs-on: macos-12
    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - id: prNumber
        run: |
          echo "${{ github.event.number }} --> github.event.number"
          echo "${{ secrets.GITHUB_REF }} --> secrets.GITHUB_REF"
          echo "${{ steps.PR.outputs.number }} --> steps.PR.outputs.number"
          echo "${{ steps.findPr.outputs.number }} --> steps.findPr.outputs.number"
          echo "${{ github.ref }} --> github.ref"
          echo "${{ github.event.pull_request.status }} --> github.event.pull_request.status"
          echo "${{ github.event.pull_request.state }} --> github.event.pull_request.state"
          echo "${{ github.event.pull_request.number }} --> github.event.pull_request.number"
          echo "should not exist --> $(cat pr-number.txt)"
